---
title: "LDP_internship_report"
author: "Alice Assmar"
date: "2025-11-17"
output: pdf_document
---
# Timeline

## Week 1 (November 3-9th, 2025)
Meeting with David Hunt (Wed 5th)

-> Folder structure - separate intermediate output from final, cleaned output

-> If possible, use SAS files instead of looping the lines of the .dat files

-> I started working with the .dat files because there were missing information in the SAS data files. Howard sent the SAS metadata on Fri, 7th, then I started working on them.

-> Ask Howard -> Should SAS files and .dat have the same info? HS - Yes, they should, but they do not have.

-> David mentioned there probably are floating point error in some of the columns

-> Add unique IDs for trawls and fishes
    - trawl unique ID - date, lake_code, trawl_number 
    - fish unique ID - date, lake_code, trawl_number, fish_id
    
## Week 2 (November 10-16th, 2025)
-> Columns trawl_location, sample_type and sample_number are not present in the SAS files.  
    - Howard said sample_type and sample_number are probably same for all rows.  
    - Athena expressed concerns about the trawl_location, and I will try to maintain the info in the final matrix.  

-> We will remove the processor/observer names because of privacy purpose - add the justification to the data_dictionary   

-> NA should be left as is.  

-> Round numbers to two decimals after point during quality check period.  

-> There are more rows in the SAS data file than in the .dat file. for year '84.  

-> "comment" column appears to be empty, if that is the case for all years, it should be removed.  

-> Create a summary table - compare SAS and .dat files - survey by day (e.g. lake 3, date - compare info)
    - recommended match and merge
    - cross check lake in every year - summarize command - count # lakes in that year
    - Count # of rows per lake, date, species and trawl.
    
-> Apple data cross checking confirmation for '77-99
    - check if there are original files to all years - looks like we don't

Meeting with David Hunt, Athena Ogden, Howard Stiff (Wed 12th)

## Week 3 (November 17-23th, 2025)
-> SAS files   "trawl85.sas7bdat",  
               "trawl86.sas7bdat",  
               "trawl87.sas7bdat",  
               "trawl94.sas7bdat",  
               "trawl97.sas7bdat",  
               "trawl98.sas7bdat".  
Contain wrongly formatted information in the metadata. It jeopardized the table merging.

-> Yulia's script worked well for .dat files from '84-'85. However, I had to adapt the script to the other years because the loop was assigning values to the wrong columns. For the year '88, I modified the "start_end_time" cleaning script, and for the '87 and '90-'99, I kept the empty lines as missing data and modified the loop to account for it.

-> Create a summary script to compare SAS and DAT files
    - some of the .dat have still issues with the loop - '89

Meeting with David Hunt, Athena Ogden, Howard Stiff (Mon 17th)

-> Next steps after the (Mon 17th) meeting:
    - check duplicates
    - correct loop year '89
    - How many records have missing duration? Calculate the duration for the missing ones
    - Commit changes as branch
    - Assemble all datasets into one giant table
    - Separate juvenile/adults
    - Add line number to source files (.dat)
    - clean name of source file (original name without path)
    - check with inventory Howard uploaded to gitHub
    - Send corrupted SAS files to David decode
    - Compile missing info in these corrupted files and send to Athena and Howard

## Week 4 (November 24-30th, 2025)
-> Steps performed after the (Mon 17th) meeting:
    - corrected loop year '89 - adapted script 88-99
    - Fixed problems with '87 (three and four lines mixed, spaces between metadata) - separate script to it
    - .dat '86 has different time format for different data blocks. Also, Missing metadata info for samples in lines 1253 - 1962 (blocks of empty lines). 
    - Commit changes as branch
    - Assemble all datasets into one giant table
    - Add line number to source files (.dat)
    - clean name of source file (original name without path)
    - check with inventory Howard uploaded to gitHub
    - Send corrupted SAS files to David decode
    - year '98 dat - last block of data is not being added (?) - fixed by adding a new line at the end of .dat file
    - reverse order of name and code in year '88 dat file for depth_m
        
-> Issues found:
    - preservative code 11 (98-99), there is no info on weight conversion or the name of it, formalin 0% ?
        - "0  0% FORMALIN - WGHD AFT 5 WKS" - written as a comment in the preservative column
        - can I add this in the preservative lookup table?
    - '99 "PROCESSED BY ALAN HIRST. COMPUTER WILL NOT ACCEPT 00 FOR DATE OF PROCESSING SO I'AM USING 99."
    - '84 .dat file with huge amount of missing data when compared to equivalent SAS file.
    - IMPORTANT: Trawl number SAS file '91 is "999" while it is "99" in equivalent .dat file!!!
    
-> Steps to be performed during quality check phase:
    - Compile missing info in these corrupted files and send to Athena and Howard
    - Check duplicates
    - How many records have missing duration? Calculate the duration for the missing ones
    - Separate juvenile/adults

-> Meeting with David Hunt, Athena Ogden, Howard Stiff (Wed 26th)
    - Use fish unique ID to combine datasets - use "update_values" command of full_join - joyn package
    - Formalin info should be different depending on the concentration. Add info to different columns
    - Check how many preservative codes there are in the data (unique()) to correct the "11" in the '98-99 data files
    - y2k bug - convert '99 to 2000 in the processing date of '99 file and flag it in the metadata and in the data frame.
    - Add to the metadata that there were data loss in .dat '84, not only in '83 and before.
    - Try standardizing columns and using cbind to concatenate same year data. Use fishID to do it and exclude duplicates later, ignoring source file column.
    - I had an issue with the pushing/pulling things from GitHub. David will help me later with this.
    
## Week 5 (December 01-07th, 2025)
-> to do:
    - Seems like there are duplicates in fish unique ID. Maybe add species code to the fishID
    - Fish total in SAS files has weird format, they are not integers. Check the original file and make it an integer.
    - y2k bug - convert '99 to 2000 in the processing date of '99 file

-> Issues found:
    - When I was converting the fish total in SAS file, I noticed that SAS '84 presented different numbers of "fish total" and "fish_id" in the metadata and trawl file. There are more fishes in the trawl file than the number reported in the metadata. e.g. sample date 1984-05-29
    - even with the species code in the fish unique ID, the codes are not unique.
    
-> Meeting with David Hunt, Athena Ogden, Howard Stiff (Mon 01st)
    - We discussed the possible ways of making the fish unique ID actually unique
    - Fish ID is an arbitrary number, and blocks of data with the same metadata, but separated in the data files, will be displayed as duplicates.
    - Use fish length and weight in the ID instead of the fish id
    - Check duplicates before combining the databases
    
## Week 6 (December 08-14th, 2025)
-> Done:
    - Removed duplicates in the individual dataframes
    - Corrected y2k bug in the '99 trawl dat file
    - Combined data frames keeping rows as duplicates
    - Fish unique ID is: TrawlDate_LakeCode_TrawlNumber_Depth_SpeciesCode_FishID_Weight_Length
    
-> Meeting with David Hunt, Athena Ogden, Howard Stiff (Wed 10th)
    - David was going to try to find a simpler way of combining the data frames because the "full_join" function was not combing all columns and rows. It combined or columns or rows.
    
## Week 7 (December 15-21th, 2025)
-> Done:
    - Collapsed duplicated rows keeping the .dat info when conflict existed
    - Flagged problematic time rows across start_time columns in .dat files (column "dat_invalid_start_time")
    - Collapse source_file columns into one

-> Needs to be done:
    - Relocate columns
    - How many records have missing duration? Calculate the duration for the missing ones
    - Separate juvenile/adults
    - Check how many preservative codes there are in the data (unique()) to correct the "11" in the '98-99 data files
    
-> Meeting with David Hunt, Athena Ogden, Howard Stiff (Wed 17th)
    - Midnight should be 00
    - Return to the .dat file script because there is an issue when converting the format of the time
    - Have one script calling other scripts
    - Create a 03_errors folder on GitHub and upload .csv files with the flagged errors
        - duplicates in the final combined data frame
        - flag which species have different "fish_total" between .sas and .dat files.
        - Errors with the start_time, end_time and duration_mi

-> Issues:
    - fish_unique_ID == "1986-04-16_161_4_15_1_4_3.73_68" - record present in both trawl85.dat and trawl86.dat. The current code keep only the first time the record appears, deleting the second row. So, the Trawl86.dat record is not kept (scale_book is different between these files). Should I keep it like that, as they seem to be duplicates, or should I keep them separately?

    - For the trawl92.sas file, the "100:MM:SS" is in the original file. It is absent in the .dat file.
    
## Week 8 (December 22-28th, 2025)
-> Done:
    - Return to the .dat file script because there is an issue when converting the format of the time
      - The issue was when re-opening the table as csv. I removed that step and saved as csv only at the end.
      - 10247 rows with wrong format.
    - Relocate columns
    - Separate juvenile/adults in fish_description
    - Check how many preservative codes there are in the data (unique()) to correct the "11" in the '98-99 data files

## Week 9 (December 29, 2025 - January 4th, 2026)
-> Done:
    - How many records have missing duration? Calculate the duration for the missing ones
    - Errors with the start_time, end_time and duration_mi

-> Issues:
    - Processor "99" should be replaced by "NA"? Replace all "999" by "NA"
    - preservative codes "9" and "98" mean "unknown", should I keep both? all become NA
    - preservative code 11 in trawl 96 = "0 0% FORMALIN - WGHD AFT 5 WKS" - does this mean "fresh"?
    - preservative code 350 = 0 0% OH - WGHD AFT 5 WKS
    - preservative code 270 = 0 0 % OH - WGHD AFTER 5 WKS
    - fish_unique_ID == 1997-09-17_69_9_15_7_1_1.35_49 - duration_min, is the "0203" = end_time?
      - correct the end time and calculate the duration
    - fish_unique_ID == "1986-04-16_161_4_15_1_4_3.73_68" - record present in both trawl85.dat and trawl86.dat. The current code keep only the first time the record appears, deleting the second row. So, the Trawl86.dat record is not kept (scale_book is different between these files). Should I keep it like that, as they seem to be duplicates, or should I keep them separately?

-> Needs to be done:
    - Combine start_time and end_time columns
    - change order .dat and .sas
    - Replace all "999" or "99" by "NA" in all columns
    - correct the end time and calculate the duration - everything with 0203 - fish_unique_ID == 1997-09-17_69_9_15_7_1_1.35_49
    - 11 -> 1 - preservative code
    - add a column duration_mi_comment
    - collapse all comments columns into one. e.g.: Duration_min: "changed from 1500?, PR 23Mar2000". include "trawl_location"
      - move Ethanol 95% as preservative_comment but keep the comment - report the change in a general comment column
        - check the frequency
        - info from trawl_location column
    - preservative code 350 = 0 0% OH - WGHD AFT 5 WKS - code 3 (typo error)
    - preservative code 270 = 0 0 % OH - WGHD AFTER 5 WKS - code 2 (typo error)
    - season - April 1st to March 31st - Check the books and season times
    - Wrong hours format that are also wrong in the original .sas and .dat files replace them by NA
    - Two columns for species: genera and species
    - standardize species_code_comment column
    - export the rows with no fish_description
    - if between FRY and Juvenile - keep Fry

## Weeks 10-11 (January 5-18th, 2026)
-> Done:
    - Checked season overlap between years. 
      - Trawl '85 has all data of Trawl '86 for April, only. 394 rows overlap
      - Trawl '90 has data from Trawl '85. 79 rows overlap
      - Trawl '97 has four rows with trawl date "31-01-1996", which should be in Trawl '95, but there is no records for January 1996 in Trawl '95 file. Neither on trawl '96 file.
      - All other Trawl files are between April 1st and March 31st of the following year
    - corrected the end time - everything with 0203
    - standardize species_code_comment column
    - Replace all "999" or "99" by "NA" in all columns
    - Two columns for species: genera and species
    - preservative code 350 = 0 0% OH - WGHD AFT 5 WKS - code 3 (typo error)
    - preservative code 270 = 0 0 % OH - WGHD AFTER 5 WKS - code 2 (typo error)
    - 11 -> 1 - preservative code
    - add a column duration_mi_comment - comments added to "time_comment" column
    - export the rows with no fish_description
    - if between FRY and Juvenile - keep Fry
    - Add "0" in the start_time. Leading 0 problems
      - Pad funcion: https://stringr.tidyverse.org/reference/str_pad.html
    - Combine start_time and end_time columns
    - Wrong hours format that are also wrong in the original .sas and .dat files replace them by NA

-> Issues:
  - Trawl '92 start time: example for date "140792", DAT shows "331", "57", "424", do these mean 03:31, 00:57, 04:24 ?
      - corrected adding leading 0 in the dat file conversion
  - Preservative_code are actualy code 3: 35 NA  0 0% ALCOHOL - WGHD AFT 5 WKS
                                          35 NA  0 0% OH - WGHD AFT 5 WKS
  - Trawl #99 - Unknown?
  - duration_mi max 
  - depth_m max
  
-> Needs to be done:
    - Compare the duration and start_time/end_time and flag the problematic rows
    - collapse all comments columns into one. e.g.: Duration_min: "changed from 1500?, PR 23Mar2000". include "trawl_location"
      - move Ethanol 95% as preservative_comment but keep the comment - report the change in a general comment column
        - check the frequency
        - info from trawl_location column
    - Check fishes lengths and weights - weird combination likely outlier
      - data dictionary - 95% range of the data is XX (species specific) - sockeye  
    - Add a note to the comment column: fish_description: Dolly Varden
        - Salvelinus malma and S. confluentus - might have unsolved taxonomic issues 

## Week 12 (January 19-25th, 2026)
-> Done:
    - collapse all comments columns into one. e.g.: Duration_min: "changed from 1500?, PR 23Mar2000". include "trawl_location"
    - Removed values greater than 20 from the scale_book column as they were sequences of value equal to the fishID count.
    - Cleaned duration_mi and depth_m columns
    - Compare the duration and start_time/end_time and flag the problematic rows
    - Add a note to the comment column: fish_description: Dolly Varden
        - Salvelinus malma and S. confluentus - might have unsolved taxonomic issues 

-> Issues:
  - What are the max values:
    - depth_m max - I believe "188" and "200" are actually "18" and "20" meters.
  - Fish ID = 1986-09-01_6_2_12_1_1_58_48
    - fish_length_mm: 48, fish_weight_g = 58, scale_book = 1.86 -> 58 mm and 1.86 g - add a comment about the change
    - This is the info present in the trawl86.dat file. 
    - 1.86 is probably the weight, but what is the length?
    - fish lengths range from ~38-63, but the ones larger than 49 mm, weight 1g or more. So probably 58mm?
    - Most fish in the same record is from scale_book '0'
  - KOKANEE - fish_unique_id 1996-07-24_2_6_14_32_1_47.98_160
    - Oncorhynchus nerka (?) - same as Sockeye? - different ecotype - Sockeye are anadromous (both marine and freshwater), Kokanee freshwater
    - code 32 nonexistent - code 25 is Kokanee, should I replace?

-> Needs to be done:
    - Replace end_time by start_time + duration_min and flag the problematic rows
      - Fix erroneous duration_mi
    - move Ethanol 95% as preservative_comment but keep the comment - report the change in a general comment column
        - check the frequency
        - info from trawl_location column
    - Check fishes lengths and weights - weird combination likely outlier
      - data dictionary - 95% range of the data is XX (species specific) - sockeye  

-> Meeting:      
    - duration_mi column
    - comment e.g. start_time end_time calc do not match duration_final, unknown explanation
        - start_time end do not match duration_final, start_time likely an error, probably at night
        - add comment on NA replaced by duration calculated from start_t and end_t
    - ggplot commands
        - duration across lakes
        - Plot the depth_m across lakes
    - depth_m max - I believe "188" and "200" are actually "18" and "20" meters. - change and add a comment likely typo
    - Keep calculated time column, but include the info in the data_dictionary and explain it very clearly
    - Re-calculation of std_weight - 'calc' - calculated from the data.
    - "scale_book > 20, likely error", but do not deleted them 
        - where the physical fish scale is - add to the data_dictionary file.
        - Include a picture in the metadata
    - Create a .csv lookup table (chk Horward's email) to standardize species_code
        - 32 - unknown life stage Kokanee

-> done:
  - depth_m max - I believe "188" and "200" are actually "18" and "20" meters. - change and add a comment likely typo
  - Keep calculated time column, but include the info in the data_dictionary and explain it very clearly
  - Create a .csv lookup table (chk Horward's email) to standardize species_code
  - calculated end_time based on start_time and duration_mi
  - Fish ID = 1986-09-01_6_2_12_1_1_58_48
      - fish_length_mm: 48, fish_weight_g = 58, scale_book = 1.86 -> 58 mm and 1.86 g - add a comment about the change

## Week 13 (January 26th-February 01st, 2026)
-> Done:
  - move Ethanol 95% as preservative_comment but keep the comment - report the change in a general comment column
        - check the frequency - 351 rows with "95% Ethanol" - preservative_code = 99 Unknown.
        - Preservative_description replaced by info from trawl_location column
  - Re-calculation of std_weight - 'calc' - calculated from the data.
  - cleaned spaces from trawl_comment (former trawl_location) column

-> Metadata:
  - Check fishes lengths and weights - weird combination likely outlier
    - data dictionary - 95% range of the data is XX (species specific) - sockeye
    
-> Meeting
  - Add a preservative code #5 for 95% Ethanol - describe this change in the data dictionary
  - Change the name of "trawl_location" comment to "trawl_comment" - originally named "xx", including general trawl location, but there is additional info
  - Gear_type - new field. grep "SEIN"  and copy to a new column. beach seine <- accurate, 
  - end_time - flag if there were errors in the end_time
  - Howard will send a list of the order of the column for the final matrix
  - Depth_m facet_wrap by lake
  - separate issues/flags from the general comments

## Week 14 (February 02nd-8th, 2026)
-> Done:
  - Organized the data_dictionary
  - Re-organized the general_comments, data_issues, and create a "data_validation_comments" column to better separate comments.
  - Organized general README file
  - Depth_m facet_wrap by lake
  
-> After Mid-internship meeting
  - Correct ATS year in the first codes to reflect season year - April 1st to March 31st
  - gear_type column - Every row with seine info will become "beach seine" and all other is "Trawl"
    - Dum1/dum2 information become NA
    - Flag all rows that have "NET", "Dum" or "7X7X7.5" info - what does this info mean?
  - sample_type column: keep as is
  - Export one preservative code summary table to send to Howard and Athena
  - Remove "data retrieved" from the time stamp
  - Report which column is "sythetic" - Created by us - or "raw_data" - from original files 


## Week 14 (February 9-15th, 2026)
-> Done:
  - Correct ATS year in the first codes to reflect season year - April 1st to March 31st
  - gear_type column - Every row with seine info will become "beach seine" and all other is "Trawl"
    - Dum1/dum2 information become NA
    - Flag all rows that have "NET", "Dum" or "7X7X7.5" info - what does this info mean?
  - sample_type column: keep as is
  - Export one preservative code summary table to send to Howard and Athena
  - Remove "data retrieved" from the time stamp
  - Report which column is "synthetic" - Created by us - or "raw_data" - from original files 
  - histogram K index species_name + age_class by lake_name
  
-> Meeting:
  - prompt the user if they want to skip any step of the project
  - Flag species with no name
      - data issue: several NAs - Trawl effort with no fishes collected
      - data issue: W weight/length - no species code issue
  - duplicates error table
      - Flag which ones are still duplicates and keep them for now.
  - Howard sharepoint - preservative code lookup table.
  - combine the survey effort by lake per year table with the total survey effort.
  - Rename the figures captions.
  
## Week 15 (February 16-22nd, 2026)
-> Done:
  - Created a .csv table to flag and correct outliers in weight and length columns.
  - Fixed gear_type rows with "DUM#" comment on sample_type or sample_number fields.
  - Reorganized calc_std_weight due to modification in fish weight column
  - Howard sharepoint - preservative code lookup table.
  - combine the survey effort by lake per year table with the total survey effort.
  - Rename the figures captions.

-> Meeting:
  - Export a table with fish_unique_ID, species name, lake name, length, weight and K index 
      - send to Howard and Athena so they can review the records
  - Flag anything greater than 2.0 K index - "Unusual size"
  - Fix "No Name Lake"
  - DUM problem - sample_number should become NA, not gear_type.


