---
title: "Living Data Program (LDP) Internship - Lakes Data In British Columbia - Trawl Biosample
  1977-1999"
author: "Alice Assmar"
date: "2026-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Agency Supervisors** Howard Stiff ([Howard.Stiff\@dfo-mpo.gc.ca](mailto:Howard.Stiff@dfo-mpo.gc.ca){.email}), Athena Ogden ([athena.ogden\@dfo-mpo.gc.ca](mailto:athena.ogden@dfo-mpo.gc.ca){.email}), Patrick Thompson ([Patrick.Thompson\@dfo-mpo.gc.ca](mailto:Patrick.Thompson@dfo-mpo.gc.ca){.email})

**CIEE LDP supervisor** David Hunt (LDP Post-Doc, McGill University)

## Introduction

The Salmon in Regional Ecosystems (SiRE) program at Fisheries and Oceans Canada conducted the Lake Enrichment Program and related surveys from 1977-2010. The extensive limnological data holdings include, among other information, fish data collected using trawls in waterbodies located in British Columbia, Canada, from 1977 to 1999, which are detailed in the report [*cite the report*]. Some species of fish have abundance and sampling data such as length, weight and life stage. The data exist in several formats, such as within published DFO reports, Excel spreadsheets, and MS Access databases, as well as SAS and DAT original formats. This folder (TRAWL_BIOSAMPLE) includes folders organized during the Living Data Project (LDP) internship (2025-2026), and the goal was to combine as many variables as possible from these data sources into a single dataset with consistent formatting and reporting standards, to be made publicly available for all Canadians and scientists.

## Folder structure

-   **00_raw_data** contains folders with raw files separated into sub-folders according to their formats. It also includes look-up tables as references for the codes. A data dictionary is provided in this folder to explain the variables and their names as given in the original data.

    -   **01_DAT** original (Apple) .dat files, from 1984–1999, and synthetic SAS outputs in tabular text format from 1977 to 1983. The SAS versions of the data from 1977-1983 (and to a lesser extent from 1984), are missing a considerable amount of the original data.
          -   SAS versions input files (1977-1983) are synthetic outputs from SAS (original data not available), presented in columns, without proper headers, whereas *.dat files from 1984 to 1999 are in the original data format as lists, with one variable per line.

    -   **02_SAS_Data** Contains .dat files converted to SAS format. Trawlyy.sas7bdat files include fish data, while Trlinfyy.sas7bdat files contain trawl information.
    -   **03_AA_look_up_tables** .csv tables comprising preservative formulas for calculating standardized weight, reference information for fish scientific names, and a reference table used to correct fish length and weight values in the final dataset.
    -   **04_YS_look_up_tables** .csv tables providing references for lake names, fish species codes, preservative codes, and weight conversion factors..

-   **01_code** includes the R codes to convert .sas and .dat files to .csv and to compare each year's tables. In addition, it includes a code to assemble all databases into one dataset, clean the columns in the final unified table and export .csv files reporting problematic rows.

-   **02_intermediate_out** includes raw individual data for each trawl year in .csv, originated from both .dat and .sas files. In addition, it includes raw combined datasets in .csv, saved before clean up process. A data dictionary is provided in this folder to explain the variables.

-   **03_errors_out** contains .csv tables with errors flagged during data cleaning steps. These tables contain only the rows presenting the errors. A data dictionary is provided in this folder to explain the variables.

-   **04_final_output** contains the final, cleaned dataset in .csv. A data dictionary is provided in this folder to explain the variables.

-   **05_ARCHIVE** includes the report, in .Rmd and .pdf, created by Alice Assmar during the Living Data Program Internship.

-   **06_Figures** Contains all figures and tables created for inclusion in the final .html data dictionary file.

-   **code** is the former code folder that includes data conversion from .dat to .csv and to read .sas and .access files.

-   **data** is the former data folder including only original .dat files and lookup tables for lake names and trawl inventories.

## How to use the codes

-   The easiest way of using this pipeline is to open the *00_run_pipeline.R* code, located in the *01_code* folder using the *LDP_ATS_RESCUE.Rproj* and click run. This code will create all necessary folder, if applicable, and run all subsequent scripts. 
    - This pipeline starts by exporting .sas and .dat databases from *00_raw_data* folder as converted .csv tables to the *02_intermediate_out* folder. 
    - Subsequently, it creates summary tables comparing the data from tables of the same year, but from different source files (.sas or .dat). 
    - Lastly, it assembles all .csv tables, cleans duplicates, export raw combined tables to *02_intermediate_out*, flags invalid or mismatch information, export error tables to *03_errors_out* and export the final, cleaned table to the *04_final_output* folder.


-   Another option is to run all scripts individually. This is advantageous if some of the steps have been previously completed because it will save you some time. Any of the following steps can be skipped or modified as needed. Please, guarantee that your working directory is set to the *LDP_ATS_Rescue* folder.
    -   Firstly, the original files should be converted to .csv tables to facilitate downstream steps. Open the *Read_Trawl_data_from_SAS_datasets.R* code, located in the *01_code* folder using the *LDP_ATS_RESCUE.Rproj* and click run. It creates all necessary folders, if they are absent from the directory, and it exports all .sas files as .csv in the *02_intermediate_out* folder. 
    -   Run all six *Read_Trawl_data_from_DAT_datasets_YYYY.R* scripts in any order you judge appropriate. It converts the .dat files in the *00_raw_data* and save them in the *02_intermediate_out* folder.
    -   Run the *summary_table.R* script for the desired year comparison, by changing the name of the trawl file in the script.
    -   Open the *Assemble_csv_dat_sas.R* script and run it. The final, cleaned dataframe is exported to the *04_final_output* folder.
