

```{r log-message, echo = FALSE}
# Data import, initial setup, figure captions, and functions

log_msg <- function(msg) {
  # function to log the KNIT process
  message(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "|", msg, "\n")
}
```

```{r read_csvs}
# Import CSVs : Acoustic, Trawl, Lakes ----

lake_codes_names_lat_longs <- read.csv("./00_data/lake_codes.csv")   # LEP lake codes, names, and lat-longs
lake_codes_names <- lake_codes_names_lat_longs %>%                   # same, but lat-longs dropped
  dplyr::select(-lake_latitude, -lake_longitude)                     # this DF can be used to tidy up lake names

# log_msg("Reading acoustic data...")

Acoustic_data_import <- read.csv("./00_data/Target_OUTPUT_data_FINAL_(1977_2007).csv") %>%
  # filter(lake_code == 255) %>%                                       # ATS Acoustics data
  left_join(lake_codes_names, by = "lake_code") %>%                  # merge proper lake_name variable by lake code
  relocate(lake_name, .after = lake_code) %>%                        # tidy order and
  select(-lake)                                                      # drop old "lake" variable

log_msg("Reading trawl data...")

Trawl_data_import <- read.csv("./00_data/Trawl_data_FINAL_1977-1999.csv") # ATS Trawl data

```

```{r global_variables}
# Global variables ----

fig_width  <- 7.5            # figure width in inches
fig_height <- 7.0            # figure height in inches  
half_height<- 2.5            # figure height for half-page plots
out_width  <- "80%"          # figure sizing to fit page
portrait   <- 11/8.5         # figure aspect ratio for 8.5 x 11 page in portrait mode
landscape  <- 8.5/11         # figure aspect ratio for 8.5 x 11 page in landscape mode
A4         <- 11.69/8.27     # figure aspect ratio for 8.5 x 14 page (A4) in portrait mode (tall)

# Lakes of Interest (Key Study Lakes) ----

lakes_of_interest <- c("Great Central Lake", "Sproat Lake", "Henderson Lake",            # Barkley Sound
                       "Kennedy Lake", "Cheewhat Lake", "Muriel Lake", "Hobiton Lake",   # Clayoquot Sound & WCVI
                       "Nimpkish Lake", "Vernon Lake", "Woss Lake",                      # ECVI
                       "Long Lake", "Owikeno Lake", "Meziadin Lake",                     # Central Coast
                       "Skidegate Lake", "Yakoun Lake", "Tahltan Lake")                  # North Coast, Haida Gwaii

# lakes_of_interest <- c("Cheewhat Lake", "Great Central Lake", "Henderson Lake")        # TEST SET
# lakes_of_interest <- c("Great Central Lake", "Hobiton Lake", "Kennedy Lake", "Long Lake")# TEST SET

```

```{r load-captions, include=FALSE}
source("03-figure_captions.R") # r code that contains all figure captions
```

```{r functions}        

fix_lake_codes_names <- function(df) {
  
  df %>%
    
    # Step 1: Fix acoustic-import lake codes
    mutate(
      lake_code = case_when(
        lake_code == 245 ~ 122,  # Quatse Lake
        lake_code == 247 ~ 121,  # Nahwitti Lake      # most of these are additional codes for existing lakes
        lake_code == 248 ~ 49,   # Fulmore Lake       # but with _2005 attached to the lake_name.
        lake_code == 249 ~ 59,   # Phillips Lake      # this code consolidates such records with original
        lake_code == 250 ~ 50,   # Heydon Lake        # lake code and name.
        lake_code == 243 ~ 50,   # Heydon Lake        
        lake_code == 244 ~ 50,   # Heydon Lake        
        lake_code == 251 ~ 237,  # Osoyoos Lake
        lake_code == 252 ~ 122,  # Quatse Lake
        lake_code == 255 ~ 241,  # Skaha Lake
        lake_code == 124 ~ 180,  # No-Name Lake -> Link Lake
        TRUE ~ lake_code)
    ) %>%
    
    # Step 2: Consolidate lake codes for data report plots & tables
    mutate(
      lake_code = case_when(
        lake_code %in% c(40, 41, 234) ~ 5,         # Kennedy
        lake_code %in% c(166, 167) ~ 107,          # Cheewhat
        lake_code %in% c(801, 802) ~ 8,            # Long
        lake_code %in% c(228, 229, 230, 231) ~ 18, # Owikeno
        lake_code %in% c(238, 239, 240) ~ 237,     # Osoyoos
        lake_code %in% c(255) ~ 241,               # Skaha
        lake_code %in% c(155, 156) ~ 62,           # Skidegate
        lake_code %in% c(159, 160, 163, 164) ~ 2,  # Sproat
        TRUE ~ lake_code
      )
    ) %>%
    
    # Step 3: Consolidate lake names (to re-assign old specific location/arm names to one name after lake-code fix)
    mutate(
      lake_name = case_when(
        lake_code == 5   ~ "Kennedy Lake",
        lake_code == 107 ~ "Cheewhat Lake",
        lake_code == 8   ~ "Long Lake",
        lake_code == 18  ~ "Owikeno Lake",
        lake_code == 237 ~ "Osoyoos Lake",
        lake_code == 241 ~ "Skaha Lake",
        lake_code == 62  ~ "Skidegate Lake",
        lake_code == 2   ~ "Sproat Lake",
        TRUE ~ lake_name)) %>%
    mutate(
      # lake_name = str_trim(str_remove_all(lake_name, "_2005")))
      lake_name = str_trim(str_replace_all(lake_name, "_2005", " Lake")),
      lake_name = str_trim(str_replace_all(lake_name, "_2007", " Lake")))
}

trim_lake_names <- function(df) {      # Clean lake names
  
  df %>% filter(!is.na(lake_name), lake_name != "NA") %>%
    
    mutate(
      lake_name = case_when(
        lake_name == "Kennedy Lake (Clay)" ~ "Kennedy",
        lake_name == "Kennedy Lake (Main)" ~ "Kennedy",
        lake_name == "Long Lake (A)"       ~ "Long",
        lake_name == "Long Lake (B)"       ~ "Long",
        lake_name == "Osoyoos Lake C"      ~ "Osoyoos",
        lake_name == "Osoyoos Lake N"      ~ "Osoyoos",
        lake_name == "Osoyoos Lake S"      ~ "Osoyoos",                
        lake_name == "Owikeno Lake (A)"    ~ "Owikeno",
        lake_name == "Owikeno Lake (B)"    ~ "Owikeno",
        lake_name == "Owikeno Lake (C)"    ~ "Owikeno",
        lake_name == "Owikeno Lake (D)"    ~ "Owikeno",
        lake_name == "Skidegate Lake NE"   ~ "Skidegate",
        lake_name == "Skidegate Lake SW"   ~ "Skidegate",
        lake_name == "Sproat Lake (Two R)" ~ "Sproat",
        TRUE ~ lake_name)) %>%
    
    mutate(
      lake_name = str_trim(str_remove_all(lake_name, "Lake")),
      lake_name = str_trim(str_remove_all(lake_name, "_2005"))) 
}

# function to output the trawl data by lake in the Appendix - see bottom
make_catch_table_list <- function(lake_name) {

  sockeye_tbl <- sockeye_tables[[lake_name]]   # check that data for the passed lake exist
  stickle_tbl <- stickle_tables[[lake_name]]

  if (is.null(sockeye_tbl) || is.null(stickle_tbl)) {
    return(invisible(NULL))}                   # if not, pass back a NULL and carry on

  catch_tbl <- full_join(
    sockeye_tables[[lake_name]],
    stickle_tables[[lake_name]],
    by = c("Date", "ATS Year")) %>%
    arrange(Date) %>%
    mutate(
      `ATS Year` = as.character(`ATS Year`),
      Lake = ifelse(is.na(Lake), lake_stix, Lake)) %>% # lake name is missing if no Sockeye, so use lake name from Sticklebacks
    dplyr::select(-lake_stix)

  flextable::flextable(catch_tbl) |>
    # flextable::set_caption(
    #   caption = paste(
    #     lake_name,
    #     "trawl catch summary by survey date for Sockeye and Stickleback.")) |>
    flextable::width(width = 1.2) |>
    flextable::separate_header() |>
    flextable::align(
      align = "center",
      part = "all") |>
    flextable::autofit()
}

check_docx_closed <- function(path = "techreport.docx") {

  if (!file.exists(path)) return(invisible(TRUE))

  tmp <- paste0(path, ".locktest")

  ok <- tryCatch({
    file.rename(path, tmp)
  }, error = function(e) FALSE)

  if (!isTRUE(ok)) {
    stop(
      paste(
        "\n\nThe file",
        path,
        "appears to be open in Word.",
        "\nPlease close the document and knit again.\n"
      ),
      call. = FALSE
    )
  }

  file.rename(tmp, path)

  invisible(TRUE)
}

make_summary_flextable <- function(lk) {

  flextable::flextable(
    summary_tables[[lk]]
  ) |>
    flextable::separate_header() |>
    flextable::align(
      align = "center",
      part = "all"
    ) |>
    flextable::autofit()
}


# make_catch_table_list <- function(lake_name) {
# 
#   sockeye_tbl <- sockeye_tables[[lake_name]]
#   stickle_tbl <- stickle_tables[[lake_name]]
# 
#   if (is.null(sockeye_tbl) || is.null(stickle_tbl)) {
#     return(invisible(NULL))
#   }
# 
#   catch_tbl <- full_join(
#     sockeye_tables[[lake_name]],
#     stickle_tables[[lake_name]],
#     by = c("Date", "ATS Year")
#   ) %>%
#     arrange(Date) %>%
#     mutate(
#       `ATS Year` = as.character(`ATS Year`),
#       Lake = ifelse(is.na(Lake), lake_stix, Lake)
#     ) %>%
#     dplyr::select(-lake_stix)
# 
#   print(names(catch_tbl))
#         
#   ft <- flextable::flextable(catch_tbl) |>
#     flextable::width(width = 1.2) |>
#     flextable::separate_header() |>
#     flextable::align(
#       align = "center",
#       part = "all"
#     ) |>
#     flextable::autofit()
# 
#   # length columns: 1 decimal place
#   ft <- flextable::colformat_num(
#     ft,
#     j = c(
#       "Sockeye Fry_Mean Length (mm)",
#       "Stickleback_Mean Length (mm)"
#     ),
#     digits = 1
#   )
# 
#   # weight columns: 2 decimal places
#   ft <- flextable::colformat_num(
#     ft,
#     j = c(
#       "Sockeye Fry_Mean Weight (g)",
#       "Sockeye Fry_SE Length (mm)",
#       "Sockeye Fry_SE Weight (g)",
#       "Stickleback_SE Length (mm)",
#       "Stickleback_SE Weight (g)",
#       "Stickleback_Mean Weight (g)"),
#     digits = 2
#   )
# 
#   ft
# }

```