# METHODS

```{r citations, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
get_citations(pkgs = c("ggplot2", "beepr", "broom", "dplyr", "ggh4x", "ggbreak", "lubridate", "officedown", "officer", "purrr", "scales", "sf", "stringr", "tidyverse", "csasdown", "flextable", "knitr", "grateful", "joyn", "progress", "tictoc", "tibble", "tools", "base", "rmarkdown"), out.dir = paste0(getwd(), "/bib"))
cite_packages(pkgs = c("ggplot2", "beepr", "broom", "dplyr", "ggh4x", "ggbreak", "lubridate", "officedown", "officer", "purrr", "scales", "sf", "stringr", "tidyverse", "csasdown", "flextable", "knitr", "grateful", "joyn", "progress", "tictoc", "tibble", "tools", "base", "rmarkdown"), out.dir = paste0(getwd(), "/bib"))
```

## Study Area of the Lake Enrichment Program
ATS work conducted in British Columbia sampled a total of 77 lakes, or 95 sites, including lake subdividions, from 1977-2007 [*MAP BC LAKES*]. The lakes surveyed in the program were located mainly in the coastal areas of British Columbia. According to @hyattResponsesSockeyeSalmon1985, the lakes shared the following characteristics: considerably low phosphorus concentrations, rapid replacement of water due to high flows, and extreme oligotrophic conditions. 

## Field Procedures
The field procedures used from 1977-2007 will be briefly mentioned in this report, but background details on methods used for acoustic limnetic fish estimations and tow net trawl biosamples are explained in detail in the following reports: @hyattLakeEnrichmentProgram1984; @hyattAcousticTrawlBased2000; @gjernesPortableMidwaterTrawling1979; @gjernesDevelopmentSpecificationsUse1986; @hyattResponsesSockeyeSalmon1985. For the LEP, at least one transect was delimited per basin and four transects per lake [@RankinRutherford1985]. Ideal techniques to assess fish population in lakes vary depending on the characteristics of the lake, such as size, depth, elevation; @maclellanEvaluationMethodsUsed2010 presented more up-to-date methods adopted by DFO to conduct fieldwork.

### Acoustic Target
The single-beam sounder used from the early 1970s to the early 1980s was the Furuno (FM 22 and FNV-3000) [@robinsonPopulationEstimatesSockeye1978], and in 1984 onward the SIMRAD was used [@gjernesDevelopmentSpecificationsUse1986]. Technical characteristics of echosounders limit their use in shallow waters, especially within the first metre of depth [@maclellanEvaluationMethodsUsed2010]. Each lake was surveyed using a series of echo-sounding transects, arranged such that the total linear distance surveyed was approximately proportional to lake area [@hyattResponsesSockeyeSalmon1985; @gjernesDevelopmentSpecificationsUse1986]. Acoustic surveys occurred at night as Sockeye salmon migrate to the surface during this time. Fish abundance was estimated using echo trace counting, with the number of echo traces divided by the sampled volume to estimate fish concentration [@gjernesDevelopmentSpecificationsUse1986].

### Trawl Biosample
Trawl netting was used to collect fish specimens for species identification and life history assessments [@robinsonSockeyeSalmonOncorhynchus1975]. This technique complemented hydroacoustic surveys by sampling the water column where hydroacoustic targets were prominent, and surface waters that were beyond the detection range of echosounders. More importantly, this sampling method enabled researchers to identify the species present in the lake from the trawl catches, and the field crew also used it to calibrate the echosounder. Trawls were conducted using a boat-towed net, typically measuring 2 × 2 × 7.5 m. Although it did not occur in our rescued trawl records, variations of the net size were reported in other studies [*e.g.*, @robinsonSockeyeSalmonOncorhynchus1975]. Most fishes were preserved in formalin, with only a small percentage of samples preserved in ethanol. Due to the effects of preservatives on the specimen's length and weight [@Shields1996EffectsOF], these measurements were taken between several weeks and months after collection. Standardized weight was calculated using provided formulas to account for differences in measurement timing and preservative. Some fish were measured fresh and therefore required no conversion. 

## Data Rescue Program

The raw data exist in several formats, such as within published DFO reports, SAS and DAT original formats. As part of the DFO-SiRE and the CIEE-LDP partnership in 2024-2025, lake acoustic and trawl survey data from 1977-2007 collected in British Columbia lakes were rescued and cleaned by data interns, overseen by postdoctoral fellows from the same program, and DFO staff. The Acoustic target data rescue was led by Yuliya Shtymburska (intern, University of Regina) and Sandra Emry (UBC postdoctoral fellow), while the trawl biosample data rescue was led by Alice Assmar (intern, McGill University) and David Hunt (postdoctoral fellow, McGill University). During the rescue program, two DFO staff, Howard Stiff and Athena Ogden, assisted with the data extraction and cleaning, and Patrick Thompson was the agency supervisor. They were not part of DFO’s ATS field crews that collected the data. Therefore, some decisions about how to clean the data were based on educated guesses. The data were rescued using R and RStudio [@base], and all scripts and output files are available in the Government Open Data repository. The data collected during the LEP were saved into annual proprietary data files titled *TARGETyy.DAT* (for acoustic) and *TRAWLyy.DAT* (for trawl). Files saved in SAS format were stored as *.sas7bdat* and named as *Trawlyy.sas7bdat* for files including fish data, while *trlinfyy.sas7bdat* files included trawl information. For both data formats, yy indicates a two-digit value representing sampling years. 

  The Acoustic and Trawl Survey (ATS) year spans from April to March, *i.e.* from 01-Apr-yy to 31-Mar-yy+1. This is the year that should be used to group data for annual analysis as it corresponds to a single cohort of age-0+ juvenile Sockeye salmon, which emerges from eggs, moves into the nursery lake after April 1, and leaves the lake as smolts the following year before the end of March. Some juvenile Sockeye salmon (age-1+) stay an extra year in the lake and leave as smolts the following year before the end of March. Note that the March 31/April 1 cut-off may not apply to all Sockeye nursery lakes; the analyst should review published data, and technical and manuscript reports in the Canadian Reports of Fisheries and Aquatic Sciences series (available at DFO libraries) to determine these dates for individual lakes of interest. The trawl biosampling data after 1999, and the acoustic target data after 2007, were sometimes available in Excel files or scanned field notes held by the Salmon in Regional Ecosystems Program at Fisheries and Oceans Canada, but the data in those Excel and scanned longhand files have not been extracted as part of the current data recovery and cleaning process.

### Acoustic target rescue program

  The acoustic target data were obtained from ASCII data files (*i.e.*, text files with suffix .DAT) generated by a PASCAL program (Pop-P). These data were originally collected using hydro-acoustic counts from echo-sounders of "fish-like-targets" (FLT) from 1977 to 2007. The .DAT files were organized by ATS year, with blocks of text specific to each lake and survey date. The text blocks consisted of a header block of meta-data (lake code, date, sounder type, etc) for each survey, followed by individual records for FLT values for each transect and depth level. Sockeye salmon and Stickleback species composition (%) – ascertained by researchers from trawl data – were appended to each record.

  The data cleaning process is explained in detail in the "Data Cleaning" section of the "DFO-LEP Acoustic Target Data Issues (1977-2007).pdf" file in the "output" folder [@zotero-item-913]. Briefly, a script was developed to compile and clean the .DAT data files using R version 4.3.1 and RStudio 2024.09.1 Build, 394. The program uses the R packages tidyverse [@tidyverse], progress [@progress], tictoc [@tictoc], tibble [@mullerTibbleSimpleData2016], and base R Tools. They were used to import raw data from .DAT files, perform data cleanup, such as duplicates analysis, and compilation into integrated .CSV output files. Output files were timestamped, and an additional annotated file with comments regarding any data issues encountered was created. All files, including a data dictionary describing all variables of the dataset, are available for downloading from the Open Data Repository [@zotero-item-913].

### Trawl biosampling rescue program

  The original trawl biosample data were also ASCII data files (.DAT) organized by ATS year but obtained from an Apple Computer caliper-based measurement program. These files were previously formatted as line files, consisting of survey-specific text blocks with a header block of trawl meta-information (*e.g.*, lake code, date, net-size, species code, etc) followed by the specimen-specific information (fish length, weight and scale book number/letter) for each indivifual fish sample. A total of 22 files, spanning from 1977 to 1999, were available to extract trawl data. However, the .DAT files available for 1977 to 1983 were saved in a tabular text format that differed from the original Apple .DAT file format. These files are the only representative datasets for the early years 1977-1983, but it is unclear what each column represents. Unfortunately, the tabular format did not fully preserve all the original data fields. These files are presumed to have been generated by SAS software, which may have over-written the original TrawlYY.DAT files with the limited tabular format. Therefore, the .DAT data files from 1977 to 1983 could not be used in the data rescue process, but the data were largely recovered from binary .SAS datasets, described below.

  An R (version 4.5.2) script was created to loop over the .DAT files to extract trawl information, facilitated by RStudio 2025.09.2 Build 418. Each loop used the total number of fish collected during a trawl event to determine how many rows to create. The trawl-level metadata was repeated for each specimen, while the specimen-specific information, such as length and weight, was recorded separately for each fish. The .DAT files did not have header names as part of the data; these were added when the data were read into R. The line number of each record was extracted from the .DAT file and included in the final table, as well as the name of their source file to increase traceability. All cleaning steps were completed using a combination of base R and the tidyverse package and its associated packages: dplyr, lubridate, stringr and tidyr. In some of the .DAT data files, the original processor included comments related to the trawl event in the metadata block. These comments were extracted from the main data columns using the stringr package and transferred to a separated column, linked to the name of the original field they were assigned to. The dates and times were standardized following the international ISO 8601 format. The lake, preservative and species names were added to the table by joining their corresponding codes to lookup tables originally created by DFO personnel. We joined these tables using the dplyr package. The screening and removal of duplicate rows were performed during quality checks. A cleaned table was created for each ATS year and saved separately as .csv. Six scripts were created to address the nuances in the data files.

Regarding the data in SAS proprietary format files (1977-1999), they were read using the haven package [@wickhamHavenImportExport2015]. These SAS files were originally derived from the tabulate .DAT files, which are no longer available in that format. After 1983, and until 1999, both files were available (except for a few corrupted SAS files), and where there were conflicts between the two, the .dat values were used. All 22 .SAS files available, which spanned from 1977 to 1999, were used to extract trawl data. As the data were already tabulated, the cleaning process involved renaming the columns to standardize them and joining the corresponding codes to lookup tables. Duplicate rows were screened and removed, and the dates and times were also standardized following the international ISO 8601 format. One script was created to loop over all .SAS files and create final, cleaned tables separated by ATS year and saved as comma delimited .CSV text files.

Unique identifiers for each trawl survey were created by concateneting fields from the following columns: Trawl_date, Lake_code, Trawl_number, and Depth_m. Additionally, unique record identifiers were also created for each fish specimen with the same information as for the trawl event, as well as species_info_code, fish_id, weight_g, and length_mm. These codes were used to identify duplicates and merge rows from different tables.

The final dataset was created by merging all the aforementioned tables. First, when applicable, the ATS year tables were merged using the full_join function of the R package joyn [@joyn], as it keeps all columns and rows from both tables. Next, a function was created to collapse duplicate rows (*i.e.*, rows with the identical fish unique identifier) into one, and in case of conflict (*i.e.*, different values in records with the same identifier), values from the original .DAT data files would be preferred over data from .SAS files. During this process, flags were included in each row (*i.e.*, in a new column) to identify the type of merge, for example, whether it was a single row (no duplicates found) or whether missing data were replaced by actual values (see document *Data_dictionary_final_dataset* on the Open Data site for greater detail). The dataset was then cleaned and standardized during the quality check step, which included but was not limited to: (1) re-calculation of end time based on the duration and start time of the trawl event; (2) calculate verification of original duration values based on through the calculation of it using start and end time of trawl event; (3) re-calculation of standardized weight based on the preservative used; and (4) investigation of weight and length outliers and mismatches in their units (*i.e.* cm/mm, g/mg). The K factor index was calculated to identify anomalous values in length and weight, and those values were adjusted where appropriate. All modification performed in the values of any column were flagged in a column called "data_issues." K factor  was calculated using the fish length in centimeters (cm) and the calculated standardized weight in grams (g), represented by *L* and *W*, respectively in the following formula:

\begin{equation}
  K = 100 \times \frac{W}{L^3}
  (\#eq:kindex-eq)
\end{equation}

## Data Visualization {#sec:math}

This report was created using R Markdown [@rmarkdown2025] and facilitated by the packages csasdown [@csasdown] and flextable [@flextable]. The citation for each R package was created with the package grateful [@grateful]. All graphs, such as boxplots, histograms and bubble heatmaps, were created using R package ggplot2 [@wickhamGgplot2CreateElegant2007; @wickhamGgplot2ElegantGraphics2016]. The viridis color scale was used to improve colour accessibility, particularly for individuals with colour blindness. Throughout this report, the dark colour represents the results obtained based on the acoustic target dataset, while the vibrant yellow represents the trawl biosample dataset. To facilitate visualization, the 16 most surveyed lakes were selected as "key lakes" and are represented in the plots presented here. The lakes included as key lakes are: Cheewhat Lake, Great Central Lake, Henderson Lake, Hobiton Lake, Kennedy Lake, Long Lake, Meziadin Lake, Muriel Lake, Nimpkish Lake, Owikeno Lake, Skidegate Lake, Sproat Lake, Tahltan Lake, Vernon Lake, Woss Lake, and Yakoun Lake.

In Figure \@ref(fig:separated-spp) the regression curve and coefficients for four different species were estimated. The regression model was used to predict the weight corresponding to 200 evenly spaced length values created to draw the smooth line on the graph. The model and equations are presented below:

-   The model fitted a linear regression performed to the natural-log-transformed values of the variables. Abbreviations: *W* = Weight in grams (calc_std_weight_g); *L* = Length in millimeter (fish_length_mm):

  $$W = aL^b$$
  $$ln(W) = ln(a) + bln(L) + \epsilon$$

-   Coefficient *b* is the slope and represents how quickly weight increases relative to the length. This is the second coefficient calculated by the R function coef(), and the formula is:  

  $$b = \frac{\sum(X_i - \overline{X})(Y_i -\overline{Y} )}{\sum(X_i - \overline{x})^2},$$

Where

  $$X_i = ln(L_{individual\ observation}),$$
  $$\overline{X} = mean\ of\ X,$$
  $$Y_i = ln(W_{individual\ observation}),$$
  $$\overline{Y} = mean\ of\ Y$$

-   Coefficient *a* represents the intercept and is the scaling constant in the length-weight equation:

  $$intercept = ln(a)$$
  $$a = e^{intercept}$$

-   *R²* is the coefficient of determination, representing how well the regression describes the observed data:

  $$R^2 = 1-\frac{\sum(Y_i - \hat{Y_i})^2}{\sum(Y_i - \overline{Y})^2} $$

  $$\hat{Y_i} = ln(a) + bln(X_i)$$
 
   
\
The equations used to calculate standard error of appendix A are presented below:
\
  
  
  - Standard deviation (SD) of the length and weight were used to calculate the standard error (SE). Abbreviations: *N* = total number of observations, *X* = either weight in grams (calc_std_weight_g) or length in millimeter (fish_length_mm):

  $$SE(\overline{X}) = SD(X) / \sqrt{N}$$
         
  -   The margin of error (MoE) was calculated at a 95% confidence interval (CI) using a t-distribution with *N − 1* degrees of freedom:
  
  $$MoE = t_{0.975,\ N - 1} \times SE$$
  
  $$ 95\%\ CI = \pm{MoE}$$
  
  
  
  
  