---
english_title: |
  Limnetic sonar fish target and bio-sample data from Acoustic-Trawl-Survey (ATS) field studies for juvenile Sockeye salmon abundance during the Lake Enrichment and Study Lakes programs, 1977-2007 
french_title: |
  Données de ciblage des poissons par sonar limnétique et données d'échantillons biologiques issues des études de terrain par chalutage acoustique (ATS) sur l'abondance des saumons rouges juvéniles pendant les programmes d'enrichissement des lacs et des lacs d'étude, 1977-2007

author: |
  Alice C. Assmar^1^,
  Yuliya Shtymburska^2^,
  Howard W. Stiff^3^,
  Athena D. Ogden^3^, 
  David Hunt^1^, 
  Sandra Emry^4^, and
  Patrick Thompson^3^

english_address: |
  ^1^McGill University\
     1205 Docteur Penfield\
     Montreal, Quebec, H3A 1B1, Canada\
  \
  ^2^Biology Department, University of Regina\
     3737 Wascana Parkway\
     Regina, Saskatchewan, S4S 0A2, Canada\
  \
  ^3^Pacific Biological Station, Fisheries and Oceans Canada\
     3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
  \
  ^4^Zoology Department, University of British Columbia\
     6270 University Boulevard, \
     Vancouver, British Columbia, V6T 1Z4, Canada
french_address: |
  ^1^Musée entomologique Lyman, Université McGill\
     21111 rue Lakeshore\
     Sainte-Anne-de-Bellevue, Québec, H9X 3V9, Canada\
  \
  ^2^Département de biologie, Université de Regina\
     3737, promenade Wascana\
     Regina, Saskatchewan, S4S 0A2, Canada\
  \
  ^3^Station biologique du Pacifique, Pêches et Océans Canada\
     3190 Hammond Bay Road\
     Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \
  ^4^Département de biologie, Université McGill\
     1205 rue Docteur Penfield\
     Montréal, Québec, H3A 1B1, Canada\
  \
  ^5^Département de zoologie, Université de la Colombie-Britannique\
     6270, boulevard University\
     Vancouver, Colombie-Britannique, V6T 1Z4, Canada

english_region: "Pacific Region"
french_region: "Région du Pacifique"

year: "2026"
report_number: "0000"

english_preamble_pages: "iv"
french_preamble_pages: "iv"
english_content_pages: "999"
french_content_pages: "999"
english_doi: "###"
french_doi: "###"
english_isbn: "###"
french_isbn: "###"
english_cat_no: "###"
french_cat_no: "###"

abstract: |
  This report presents hydro-acoustic and trawl biosampling data collected by Fisheries and Oceans Canada (DFO) personnel as part of the Lake Enrichment and Study Lakes Program (LEP) from 1977 to 2007. The LEP collected acoustic data using echosounders and fish catch data using boat-towed trawl nets. Data from the Acoustic and Trawl Survey (ATS) were originally stored in proprietary formats, and historical conversions between file formats resulted in data loss. To recover the legacy data, DFO personnel partnered with the Canadian Institute for Ecology and Evolution Living Data Project (CIEE-LDP) and hired two then-graduate students to undertake the data rescue project.

  The recovered data were cleaned and standardized using multiple versions of R and RStudio. The project began in late 2024 and was completed in early 2026. In total, 177,541 records from original trawl biosampling files covering 1977 to 1999 were recovered, along with 123,819 records from original hydro-acoustic files covering 1977 to 2007. Both datasets are openly available through the Government of Canada Open Data repository, along with data dictionaries describing the variables, intermediate tables saved as comma-separated value (CSV) files, and metadata documenting data issues identified during the rescue process.

  The goal of this report is to disseminate the standardized datasets and provide a graphical overview of common methods used during ATS trips, as well as biological patterns observed across key study lakes and years.

output:
 csasdown::techreport_docx:
   french: false
knit: (function(input, ...) csasdown::render())
bibliography: ["bib/DFO-ATS-Report-refs.bib", "bib/grateful-refs.bib"]
---

```{r warning-techreport, include=FALSE}
warning(
  "\n*** IMPORTANT ***\n",
  "Please ensure techreport.docx is closed before rendering is complete!***")
```

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)

opts_chunk$set(
  #  cache = TRUE,     # cache all chunks?
  #  autodep = TRUE,   # try to guess which chunks depend on which in cache?
  fig.width = 6,       # 'internal' plotting figure width (inches)
  out.width = "80%",   # output plotting width; adjust here or by chunk if desired
  fig.asp = 1 / 1.618, # golden ratio; adjust here or by chunk if desired
  dpi = 150,           # adjust to taste; larger = higher resolution but larger file size
  warning = FALSE, 
  message = FALSE)
```

```{r load-libraries-csasdown}
library(csasdown) # for new_appendix(), current_appendix(), appendix_table_caption()
library(flextable) # recommended package for adding tables
```

```{r table-settings}
# recommended table settings to match CSAS table style and accessibility standards
flextable::set_flextable_defaults(
  font.size = 10,
  padding.left = 3, 
  padding.right = 3, 
  padding.top = 1, 
  padding.bottom = 1,
  na_str = "-",
  theme_fun = "theme_booktabs")
```

```{r load-libraries-user}
library(beepr)
library(broom)
library(dplyr) 
# install.packages("ggh4x")
library(ggh4x)
# install.packages("ggbreak")   # run once
library(ggbreak)
library(ggplot2) 
library(grateful)
library(lubridate)
library(officedown)
library(officer)
library(purrr)
library(scales)
library(sf)
library(stringr)
library(tidyverse)
# add more packages here as needed

```
