%LET  yy = 87 ;            	* Only place to change year ;
%LET  firstobs = 1 ;    	* Set to first record to process in ASCII file ;
*=======================================================================*
|                                                                       |
|                              TRAWL87.SAS                              |
|                                                                       |
| WRITTEN BY : j.e.radziul,t.e cone (jan 86) for LEP                    |
| MODIFIED   : h.h.stiff (nov 90) For use of TRAWLyy.SSD with BIOMASS DB|
|                                 Use this program as basis for other   |
|                                 years if creating new yearly program. |
|                                                                       |
| 1. sub/AAAAAAAA/trlyr/30:end                                          |
|  . name data file, end in year of plankton sampling                   |
|  . 11 substitutions                                                   |
|  . eight positions maximum in name                                    |
|                                                                       |
| 2. Sub/BBBBBBBB/trlinfyr/30:end                                       |
|  . 6 substitutions                                                    |
|                                                                       |
| 3. Sub/CCCCCC/ddmmyy/30:end                                           |
|  . 2 Substitutions                                                    |
|  . put current date into label                                        |
|                                                                       |
| 4. Sub/DDD,DDD/per1,per2/30:end                                       |
|  . 2 Substitutions                                                    |
|  . put in initials of people working on the file                      |
|                                                                       |
| 5. Sub/XX/yr/30:end                                                   |
|  . 5 substitutions                                                    |
|  . enter year of sampling date                                        |
|                                                                       |
| 6. Check libname statements                                           |
|                                                                       |
|                                                                       |
|                                                                       |
| This program reads APPLE data files generated by the CALIPER program  |
| and assembles the data into two SAS datasets:                         |
|       1) trawl86.SSD, which contains Trawl sampling data              |
|          sorted by lake, sample date, Trawl number and species        |
|       2) trlinf86.SSD, which contains the background information for  |
|          each sample (also sorted by lake, sample date, trawl number  |
|          and species                                                  |
|                                                                       |
| Some reformatting of the APPLE files may be necessary before running  |
| trawl86.SAS.  Make sure that the background information takes up 15   |
| lines at the start of each sample and that there are no blank lines   |
| between samples.                                                      |
| An example of how the data file should look:                          |
|     SAS variable    APPLE file       Explanation                      |
|         name          code                                            |
|     ------------    ----------       -----------                      |
|  1   procdate        100182          date counted in DDMMYY format    |
|  2   observer        8               processor (see OBSFMT.SFN)       |
|  3   system          28              lake code (see SYSFMT.SFN)       |
|  4   date            220981          sample date in DDMMYY format     |
|  5   dummy1          1               in lake sample                   |
|  6   dummy2          tr(awl)         type of sample                   |
|  7   trwlnmbr        1               trawl number (sample)            |
|  8   hh1,mm1 hh2 mm2 2345-2400       used to build statime & endtime  |
|  9   duration        15              trawl duration                   |
| 10   depth           25              depth of trawl                   |
| 11   fspecies        1               fish species                     |
| 12   comment         tr 3-4          trawl location                   |
| 13   prsrv           1               preservative code                |
| 14   nmbrfish        63              number of fish in sample         |
| 15   length          78              length                           |
| 16   weight          1.23            weight                           |
| 17   scale           0               scale number                     |
| 18   sclbook         A               only present if scale > 0        |
|                                      ELSE scale = 0                     |
|                                                                       |
| TO RUN : modify LIBNAME and INFILE statements to access .DAT file to  |
|          be processed. Submit to BATCH QUEUE. (If .DAT file contains  |
|          a large number of samples, submit to NIGHTBATCH.)            |
|                                                                       |
|                                                                       |
| INPUT  : trawl87.DAT                                                  |
| OUTPUT : trawl87.SSD trlinf87.SSD                                     |
|                                                                       |
|                                                                       |
| GLOBAL FORMATS : SYSFMT.SFN                                           |
|                  OBSFMT.SFN                                           |
|                  FSPFMT.SFN                                           |
| LOCAL FORMATS  : AGED.SFN                                             |
|                  PRSRV.SFN                                            |
*======================================================================*;

LIBNAME  io       v609  "[LEP.JUVENILE.TRAWL87]" ;
LIBNAME  library  v609  "[LEP.FMT]" ;

OPTIONS  OBS = MAX  ERRORABEND  LS=132  PS=52 ;

FILENAME  trawl  "TRAWL&yy..DAT" ;

*=====================================================================*
| Creation of LOCAL SAS formats for use only with the TRAWL data base |
*=====================================================================*;

PROC FORMAT ;
     VALUE aged  0 = 'No Scale'        1 = 'Scale & Aged'
                 2 = 'Scale - Poor'    3 = 'Scale - Regen.'
                 4 = 'Scale - Unsure'  5 = 'Defaulted'      6 = 'No Scale-Rcnld';

*---------------------------------------------------------------------*
| Format for "AGED" field - a qualitative indicator of the age values |
| assigned to a fish.                                                 |
*---------------------------------------------------------------------*;

   VALUE prsrv   0 = 'Fresh'           1 = 'Form/5wks'    2 = '70% ETOH/5wks'
                 3 = '50% ETOH/5wks'   4 = 'Form/>5mo'
                95 = 'Form/1-2d'      96 = 'Form/3wks'
                97 = 'Form/4wks'      99 = 'Form/Assumed'
                98 = 'Unknown' ;

*---------------------------------------------------------------------*
| Format for "PRSRV" field - The preservation technique used before   |
| the fish were weighed.                                              |
*---------------------------------------------------------------------*;

*-----------------------------------------------------------------------*
| Build a complete data set with all fields coded for each record. The  |
| records and background info will be extracted and seperated from this |
| temporary set in following steps.                                     |
*=======================================================================*;

DATA input filler ;
     RETAIN    linenmbr 0  inputmod ;
     INFILE    trawl  MISSOVER  EOF = fin  FIRSTOBS = &firstobs ;
     INFORMAT  comment  $char100.  procdate DDMMYY.  dummy1 dummy2 $CHAR10.  date DDMMYY.;
     LENGTH    date procdate statime endtime duration length weight stdwght 4
               nmbrfish depth fishnmbr endtime statime 3
               observer prsrv fspecies trwlnmbr duration depth
               scale system linenmbr i hh1 mm1 hh2 mm2 inputmod 3
               obsname $ 2  sclbook $ 1 ;
     FORMAT    scale 3.  statime endtime TIME5.
               fishnmbr nmbrfish 3.  system sysfmt.  date procdate DATE7.
               prsrv  prsrv.  fspecies fspfmt.  observer obsfmt.
               stdwght weight 6.2  trwlnmbr depth 3.  duration 5.;
     DROP      month year hh1 mm1 hh2 mm2 dummy1 dummy2 i linenmbr inputmod obsname ;
     LABEL     depth    = 'Depth'  duration = 'Duration'  nmbrfish = 'Number of Fish'
               procdate = 'Process Date'  prsrv = 'Preservative'  observer = 'Processor'
               endtime  = 'End time'  statime = 'Start time'  scale = 'Scale No.'
               sclbook  = 'Scale Book'  comment = 'Comments'  fishnmbr = 'Fish #'
               system   = 'System'  length = 'Length (mm)'
               date     = 'Sample Date'  fspecies = 'Species'  statime = 'Start time'
               endtime  = 'End time'  stdwght = 'Standardized Weight (g)'
               trwlnmbr = 'Trawl #'  weight = 'Weight (g)';
     INPUT     procdate / observer obsname / 
               system / date / dummy1 / dummy2 $CHAR10. / trwlnmbr;
     year      = YEAR ( date ) ;  month = MONTH ( date ) ;
     INPUT     hh1 1-2 mm1 3-4 hh2 6-7 mm2 8-9;
     INPUT     duration / depth / fspecies / comment 1-100 / prsrv / nmbrfish;
     IF        ( system = 5 or system = 40 or system = 41 ) and fspecies = 2  THEN DO ;
               IF INDEX ( comment, 'FRY' ) > 0  THEN  fspecies = 26 ;  ELSE
               IF INDEX ( comment, 'SUB' ) > 0  THEN  fspecies = 27 ;  ELSE
               fspecies = 2 ;    
	       END ;          * Assign code for Kennedy stickleback fry and subadults ;
*    IF        ( system = 5 or system = 40 or system = 41 ) 
               THEN PUT / system sysfmt. 
               'Fish code : ' fspecies 2. ' ' fspecies fspfmt. comment $char100. ;
*              Make sure non-Kennedy stickles are assigned fsp=2 regardless of life stage... ;
     IF        ( system NE 5 & system NE 40 & system NE 41 ) & 
               ( fspecies = 26 or fspecies = 27 )  THEN  fspecies = 2 ;  
     IF        ( YEAR = 19&yy & MONTH < 4 ) or ( YEAR = 19&yy + 1 & MONTH > 3 )   
               THEN PUT  / 'Error: ' system=sysfmt.  procdate=DATE7.  date=DATE7.
               observer=obsfmt. / "       Data not from 19&yy trawl year at line " linenmbr '.' ;
     IF        trwlnmbr < 1  THEN PUT
               / 'Error: ' system=sysfmt.  procdate=DATE7.  date=DATE7.
               observer=obsfmt. / '       Background information missing after line ' linenmbr '.' ;
     linenmbr  + 14 ;

     *--------------------------------------------------------------*
     | The factors used in the calculation of standardized weights  |
     | are documented in SMOLTS.DOC.                                |
     *--------------------------------------------------------------*;

     IF        ( year = 1984 & month > 3 ) or ( year = 1985 & month < 4 )  or  
               ( year = 1985 & month > 3 ) or ( year = 1986 & month < 4 )  or  
               ( year = 1986 & month > 3 ) or ( year = 1987 & month < 4 )  or  
               (( SUBSTR ( UPCASE ( obsname ), 1, 2 ) = 'ER' )  &
               (( year = 1987 & month > 3 ) or ( year = 1988 & month < 4 )))
               THEN  inputmod = 3 ;  ELSE  inputmod = 4 ;
*    PUT       system sysfmt. ' ' date DATE7. ' ' observer obsfmt.  
	       obsname $CHAR2. ' ' nmbrfish=3. ' ' inputmod=1. ;
     DO        i = 1 to nmbrfish ;
               fishnmbr = i ;
               IF  inputmod = 3  THEN INPUT  length / weight / scale ;  ELSE 
               INPUT  length / weight / scale / sclbook ;
               IF  prsrv = 0  THEN stdwght = weight ;  ELSE
               IF  prsrv = 1 | prsrv = 99  THEN  stdwght = weight/1.115100; ELSE
               IF  prsrv = 2  THEN  stdwght = weight/0.868429;  ELSE
               IF  prsrv = 3  THEN  stdwght = weight/0.832408;  ELSE
               IF  prsrv = 4  THEN  stdwght = weight/1.075312;  ELSE
               IF  prsrv = 95 THEN  stdwght = . ; ELSE
               IF  prsrv = 96 THEN  stdwght = weight/1.116898;  ELSE
               IF  prsrv = 97 THEN  stdwght = weight/1.137408;  ELSE
               IF  prsrv = 98 THEN  stdwght = . ; ELSE stdwght = .;
/*             IF  scale > 0  THEN INPUT  sclbook ;  ELSE INPUT ;  */
/* fin:        IF  scale = 0  THEN  sclbook = . ;                  */
fin:           statime = HMS ( hh1, mm1, 0 );
               endtime = HMS ( hh2, mm2, 0 );
               OUTPUT  input ;
               END ;
     IF        scale > 0  THEN PUT  
               / 'Note : ' system=sysfmt.  procdate=DATE7.  date=DATE7.
               trwlnmbr=3.  nmbrfish=4.  observer=obsfmt. / '       Scale book used at line ' linenmbr '.' ;
     IF        ( year = 1984 & month > 3 ) or ( year = 1985 & month < 4 )
               THEN  linenmbr + nmbrfish * 3 ;
     ELSE      linenmbr + nmbrfish * inputmod ;
     IF        nmbrfish = 0  THEN OUTPUT  filler ;
     RUN ;

DATA subset ;
     SET   filler ;
     IF    nmbrfish = 0 ;
     DROP  scale sclbook length weight stdwght fishnmbr ;
     fspecies=. ;
     prsrv=. ;
     RUN ;

PROC SORT  DATA = input  OUT = pretwo;
     BY    system date trwlnmbr fspecies fishnmbr ;
     RUN ;

*=========================================================*
| Background information dataset creation.                |
| PROC MEAN is used to generate this dataset.  The ID     |
| statement includes variables in the output but not in   |
| the analysis.                                           |
*=========================================================*;

PROC MEANS   DATA = pretwo  NOPRINT;
     BY      system date trwlnmbr fspecies;
     ID      procdate comment ;
     VAR     statime endtime duration depth nmbrfish prsrv observer ;
     OUTPUT  OUT = summary  MEAN = statime endtime
             duration depth nmbrfish prsrv observer ;
     RUN ;

DATA io.trlinf&yy (LABEL="19&yy Trawl Data Bkgrnd Info &SYSDATE" );
     LENGTH  statime endtime duration 4  depth nmbrfish prsrv observer 3 ;
     DROP    _FREQ_ _TYPE_ ;
     SET     summary subset ;
     RUN ;

PROC CONTENTS  DATA = io.trlinf&yy;  RUN ;

DATA io.trawl&yy (LABEL="19&yy Trawl data &SYSDATE");
     SET   pretwo ;
     DROP  procdate statime endtime comment duration nmbrfish prsrv ;
     RUN ;

PROC CONTENTS  DATA = io.trawl&yy;  RUN ;

